### ISSUE TITLE
Tests fail to compile in 7.0.0: https://github.com/softwareQinc/qpp

### ISSUE THREAD

**Issue by yurivict** [softwareQinc/qpp#196]
```
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:6:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/qpp.hpp:75:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:43:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entropies.hpp:44:
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/functions.hpp:523:21: error: 'bdcSvd' following the 'template' keyword does not refer to a template
  523 |         rA.template bdcSvd<Eigen::ComputeFullU | Eigen::ComputeFullV>();
      |            ~~~~~~~~ ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:379:21: note: in instantiation of function template specialization 'qpp::svd<Eigen::Matrix<std::complex<double>, -1, -1>>' requested here
  379 |     auto const sv = svd(transpose(reshape(rA, dims[1], dims[0])));
      |                     ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:221:20: note: in instantiation of function template specialization 'qpp::schmidt<Eigen::Matrix<std::complex<double>, -1, 1>>' requested here
  221 |     auto const t = schmidt(psi, {dA, dB});
      |                    ^
/usr/local/include/eigen3/Eigen/src/SVD/BDCSVD.h:1359:22: note: declared as a non-template here
 1359 | MatrixBase<Derived>::bdcSvd(unsigned int computationOptions) const
      |                      ^
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:6:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/qpp.hpp:75:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:43:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entropies.hpp:44:
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/functions.hpp:567:24: error: 'bdcSvd' following the 'template' keyword does not refer to a template
  567 |     return rA.template bdcSvd<Eigen::ComputeFullU>().matrixU();
      |               ~~~~~~~~ ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:157:12: note: in instantiation of function template specialization 'qpp::svdU<Eigen::Matrix<std::complex<double>, -1, -1>>' requested here
  157 |     return svdU(transpose(reshape(rA, dims[1], dims[0])));
      |            ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:227:29: note: in instantiation of function template specialization 'qpp::schmidtA<Eigen::Matrix<std::complex<double>, -1, 1>>' requested here
  227 |     auto const basisA_ref = schmidtA(psi, {dA, dB});
      |                             ^
/usr/local/include/eigen3/Eigen/src/SVD/BDCSVD.h:1359:22: note: declared as a non-template here
 1359 | MatrixBase<Derived>::bdcSvd(unsigned int computationOptions) const
      |                      ^
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:6:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/qpp.hpp:75:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:43:
In file included from /usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entropies.hpp:44:
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/functions.hpp:588:24: error: 'bdcSvd' following the 'template' keyword does not refer to a template
  588 |     return rA.template bdcSvd<Eigen::ComputeFullV>().matrixV();
      |               ~~~~~~~~ ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/include/qpp/entanglement.hpp:224:12: note: in instantiation of function template specialization 'qpp::svdV<Eigen::Matrix<std::complex<double>, -1, -1>>' requested here
  224 |     return svdV(transpose(reshape(conjugate(rA), dims[1], dims[0])));
      |            ^
/usr/ports/misc/quantum++/work/qpp-7.0.0/unit_tests/tests/entanglement.cpp:230:29: note: in instantiation of function template specialization 'qpp::schmidtB<Eigen::Matrix<std::complex<double>, -1, 1>>' requested here
  230 |     auto const basisB_ref = schmidtB(psi, {dA, dB});
      |                             ^
/usr/local/include/eigen3/Eigen/src/SVD/BDCSVD.h:1359:22: note: declared as a non-template here
 1359 | MatrixBase<Derived>::bdcSvd(unsigned int computationOptions) const
      |                      ^
3 errors generated.
```

clang-19.1.7
FreeBSD 15 STABLE
